#https://www.baeldung.com/java-mongodb
#https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
#http://localhost:8081/

services:

  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - pn

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    links:
      - mongodb_container
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb_container
    networks:
      - pn

volumes:
  mongodb_data_container:

networks:
  pn:
    name: pn
    driver: bridge